name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOOS: windows
            GOARCH: "amd64"
            ext: ".exe"
          - GOOS: windows
            GOARCH: "386"
            ext: ".exe"
          - GOOS: windows
            GOARCH: "arm64"
            ext: ".exe"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install UPX
      run: sudo apt-get update && sudo apt-get install -y upx-ucl

    - name: Build the application
      shell: bash
      run: |
        go install github.com/tc-hib/go-winres@latest
        go generate
        GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -ldflags="-s -w -H windowsgui" -o bin/umpv

    - name: Compress with UPX
      run: upx --best --lzma -o umpv${{ matrix.ext }} bin/umpv || mv bin/umpv umpv${{ matrix.ext }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: umpv-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: umpv${{ matrix.ext }}
