name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            ext: ".exe"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install UPX on Windows
      if: matrix.os == 'windows-latest'
      run: choco install upx

    - name: Build the application
      shell: bash
      run: |
        GOARCH=386 go build -ldflags="-s -w -H windowsgui" -o bin/umpv

    - name: Compress with UPX
      run: upx --best --lzma -o umpv${{ matrix.ext }} bin/umpv

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: umpv-${{ matrix.os }}
        path: umpv${{ matrix.ext }}
